/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package awesomesauceproject;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author thsun4006
 */
public class windowQuiz extends javax.swing.JFrame {
    windowMainMenu menu;
    private windowResults windowResults;
    
    Question q1 = new Question(); // question object
    Question[] questionArray = new Question[10]; // question array
    
    /**
     * Creates new form Quiz
     */
    
    public windowQuiz(windowMainMenu m) {
        initComponents();
        menu = m;
        
        // reading question file and adding question objects into a question array
        try{
            File f = new File("src/awesomesauceproject/questions.txt");
            Scanner s = new Scanner(f);
            String question;
            String a1;
            String a2;
            String a3;
            String a4;
            int answerNum;
            
            // reading file
            for (int i = 0; i < questionArray.length; i++) {
                question = s.nextLine();
                a1 = s.nextLine();
                a2 = s.nextLine();
                a3 = s.nextLine();
                a4 = s.nextLine();
                answerNum = Integer.parseInt(s.nextLine());
                
                q1 = new Question(question, a1, a2, a3, a4, answerNum); // instantiating question object
                questionArray[i] = q1; // putting question object into question array
            }
            
        } catch(FileNotFoundException e) {
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (windowResults == null) {
            windowResults = new windowResults(this, menu);
        }
        
    windowResults.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
